# Generated by Django 5.1.2 on 2024-10-18 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enter', models.BooleanField(default=None, verbose_name='Пользователь вошёл')),
                ('num_pass', models.CharField(max_length=600, verbose_name='Номер пропуска')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата прохода')),
                ('gate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit', to='api.gate', verbose_name='КПП')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit', to='api.useros', verbose_name='Пользователь ОС')),
            ],
            options={
                'verbose_name': 'Проход пользователя ОС',
                'verbose_name_plural': 'Проходы пользователей ОС',
                'ordering': ('date',),
            },
        ),
    ]
