# Generated by Django 5.1.2 on 2024-10-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='gate',
            name='working_hours_up_to',
            field=models.TimeField(default=None, null=True, verbose_name='Время работы, до'),
        ),
    ]
